# See LICENSE file for full copyright and licensing details.

{
    'name': 'Ecole',
    'version': '12.0.1.0.0',
    'author': 'Ameni & Soumaya',
    'summary':'Ce module a été ecrit durant la période du notre projet fin Etudes',
    'category': 'Ecole',
    'license': "AGPL-3",
    'complexity': 'easy',
    'Summary': 'module pour gestion ecole',
    'depends': ['hr', 'crm', 'account'],
    'data': ['security/ecole_security.xml',
             'security/ir.model.access.csv',
             'wizard/terminate_reason_view.xml',
             'wizard/wiz_send_email_view.xml',
             'views/eleve_view.xml',
             'views/ecole_view.xml',
             'views/enseignant_view.xml',
             'views/parent_view.xml',
              'views/statistiques_descipline_view.xml',
             'data/eleve_sequence.xml',
             'wizard/assign_roll_no_wizard.xml',
             'wizard/move_standards_view.xml',
              'wizard/Add_eleve.xml',
             'views/rapport_view.xml',
             'views/carte_identite.xml',
             'views/template_view.xml',
             'views/emploie_view.xml',
             'views/emploie.xml',
             ],
    'demo': ['demo/ecole_demo.xml',
    'demo/emploie_demo.xml'],
    'installable': True,
    'application': True
}
