# See LICENSE file for full copyright and licensing details.

{
    'name': 'School',
    'version': '12.0.1.0.0',
    'author': 'Ameni & Soumaya',
    'summary':'This module was written during the period of our end of studies project.',
    'category': 'School',
    'complexity': 'easy',
    'Summary': 'A Module For School Management',
    'images': ['static/description/EMS.jpg'],
    'depends': ['hr','hr_pyzk','web_notify'],
    'data': ['security/school_security.xml',
             'security/ir.model.access.csv',
             'data/TestAttenanceStudent.xml',
             'data/attendance_student_daily.xml',
             'data/student_sequence.xml',
             'views/student_view.xml',
             'views/school_view.xml',
             'views/teacher_view.xml',
             'views/parent_view.xml',
             'views/template_view.xml',
            'views/timetable_view.xml',
            'wizard/report_statistic_discipline/statistic_view.xml',
             'wizard/report_statistic_discipline/stat_discipline.xml',
             'wizard/report_statistic_discipline/report_stat.xml',
             'wizard/wizard_settings_discipline.xml',
             'wizard/school_attendance_device.xml',
             'wizard/move_standards_view.xml',
            'wizard/terminate_reason_view.xml',
             'wizard/wiz_send_email_view.xml',
             'report/ticket.xml',
             'report/report_view.xml',
             'report/identity_card.xml',
             ],

    'installable': True,
    'application': True
}
